### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by scalvin1** [kurtjd/hack-computer#1]
I tried running cadet1620's Trig.hack (26016 instructions) in emulator --> no go.
the assembler disassembles it but there are problems, it does not re-assemble and I find a line 'A=' which is clearly problematic.

I was looking at your vmtranslator because I want to reduce my hack sizes to <32k, I see that there is still some potential, especially in combining instructions like e.g. AMD=M-1 with or without jumps... 
(AMD=M-1 instead of M=M-1, D=M, A=M)

Great work in C, by the way!
JK- spin flipper 2010 ... g m ai l 

[attached.zip](https://github.com/kurtjd/hack-computer/files/7854120/attached.zip)

**Comment by kurtjd** [comment]
Thanks for the heads up!

<del>Could you clarify what you mean by 'A=' is problematic? It seems according to the [spec](https://b1391bd6-da3d-477d-8c01-38cdf774495a.filesusr.com/ugd/44046b_d70026d8c1424487a451eaba3e372132.pdf) that A is a valid destination register.</del>

Disregard that last bit, I see what you mean. There are lines that are ONLY `A=`. I'll have to look into that.
**Update**: It looks like I was missing a single 0 in the `A-D` compute translation. Should be fixed now.

I also noticed there are lines such as `dest=comp;JMP` in the disassembled Trig.hack. On further review of the spec that seems to be valid, however I never accounted for that (my code only handles jumps in the form of `comp;JMP` hence why an error is thrown about an invalid compute). I'll work on fixing that.
**Update**: This should be fixed now. Disassembling Trig.hack and then reassembling produces an identical binary to the original Trig.hack.

Yeah I was having trouble getting my assembled hack binaries to fit in the 32k of ROM as well. You may have already seen, but I saw big improvements by not repeating the frame saving/return code for every function call and instead storing it once in the beginning of the binary and jumping to it when necessary. Though that still is obviously not enough when trying to combine any non-trivial program with the OS code. Those are some good suggestions though and I'll see if I can incorporate them.

Thanks again!

**Comment by scalvin1** [comment]
Thanks for checking this! Can you push the changes to the emulator too please?
I think your emu is great. The only other one I found was written in rust (which is not bad), but it started pulling in 1GB worth of cargo just for compiling on my Debian box... :-/

**Comment by kurtjd** [comment]
Are there issues in the emulator as well? I believe it uses different logic than the assembler but maybe I'm forgetting something.

And thanks! Yeah I just tried to keep mine simple to make testing with it easy.

**Comment by scalvin1** [comment]
The emulator will presently not run the Trig.hack file from above. I guess by the same rarely used instructions as was the issue with your dis/assembler.

On a different note, I visualized memory management in the screen memory segment.
Post and asm files here:
http://nand2tetris-questions-and-answers-forum.52.s1.nabble.com/New-Heap-Management-algorithm-Coursera-version-td4032026.html

**Comment by kurtjd** [comment]
Just wanted to let you know I am working on this and hopefully have a fix soon. And that's really cool! It's impressive the clever things you and other people are able to to with such a simple machine.

**Comment by scalvin1** [comment]
I found the problems. Will send you a pull request.
Simple fix after some debugging: Your code did not handle CR-LF line endings in Hack files well. Silly Windows.
Also fixed that my hack files did not work the keyboard correctly. Tranlate lower case keys to upper and it behaves as in the official CPU Emulator.
